### ISSUE TITLE
StarField Example Projections

### ISSUE THREAD

**Issue by eirizarry** [NASAWorldWind/WebWorldWind#373] opened 2017-11-20 23:42 UTC
### Description

(Mobile testing) There is no option to view this example in different projections. All projections are listed, but you cannot select them for viewing. Also seen in Measurements, and WMTS.

### Steps to Reproduce

Open the StarField.html example

**Expected behavior:** [What you expect to happen]

Be able to between projections

**Actual behavior:** [What actually happens]

Static list

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Operating System and Version

iOS 10.3/Safari 

### Additional Information

Since this is a testing on mobile, it the examples seen on the website and not the release candidate on GitHub.

**Comment by pdavidc** [comment] 2017-11-21 17:18
Possible duplicate of #340. Needs confirmation once HTTP-based app/example resources are repaired.

**Comment by Beak-man** [comment] 2017-11-23 02:05
Confirmed. This issue is fixed when loading external libraries and CSS files via `https`.

**Comment by pdavidc** [comment] 2017-11-23 02:17
Closed as duplicate of #340

**Closed by pdavidc** 2017-11-23 02:17 UTC
Labels: release-0.9.0
