### ISSUE TITLE
Top level tile for a WMTS CRS3857 layer has no volume

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WebWorldWind#545] opened 2018-03-15 15:18 UTC
### Description
A WMTS CRS 3857 layer of US national forests was disappearing and reappearing as I panned and tilted the globe.  I traced the code and discovered that sometimes the view frustum didn't intersect the top level tile(s). When this occurred the layer wouldn't be displayed.  I rendered the tile extents (BoundingBox) and discovered the top level tile has no volume.

The layer that manifests this issue has a single top level tile that spans the hemispheres (+/-180 longitude, +/-85 latitude).

### Illustration
Here are three coincident views of the globe to document the bounding box problem. The first two images are for orientation, the third image documents the problem.

The following image is for reference and orientation. It shows the BlueMarble layer and a WMTS CRS 3857 overlay of US national forests.
![image](https://user-images.githubusercontent.com/191515/37470046-e020888c-2823-11e8-89f4-89b528f9bea8.png)

 ---

The following image shows just the WMTS layer of US national forests 
![image](https://user-images.githubusercontent.com/191515/37470061-e6c82ab4-2823-11e8-85df-c2ab777b9064.png)

---

This image shows the bounding boxes (volumes) for the WMTS layer. Note the level 0 bounding box appears to have no volume.
![image](https://user-images.githubusercontent.com/191515/37470075-ecbe6f28-2823-11e8-860f-52263318b123.png)

**Comment by PJHogan** [comment] 2018-03-15 16:01
Sure helps to have a 'super user' pounding on app behavior, and with an interest to get to the bottom of things!

https://en.wikipedia.org/wiki/Nick_Bottom

**Comment by pdavidc** [comment] 2018-03-15 17:10
@emxsys Thanks for looking into this. First, I think these types of issues will arise as long as we're attempting to align WorldWind's internal tiling scheme with that of an external data source. I have it in my roadmap to address this.

The problem is a mis-match of expectations between the WMTS implementation and what WorldWind's tiling scheme really supports. WorldWind's tiled imagery infrastructure is not designed to support tiles that span the globe in longitude or latitude. Sector.setToBoundingBox constructs a box using a set 3x3 sample points. When the sector spans -180 to 180 longitude, those sample points lie in the YZ plane, and do not capture the box's geometry on the X axis.

Again, I'm convinced the better long term solution is to decouple WorldWind's display tiles from those of the data source. In the meantime, we can detect this case in Sector.setToBoundingBox and adjust accordingly.

**Comment by pdavidc** [comment] 2018-03-15 22:00
FYI, This pull request depends on the fix in #547, which I chose to separate in order to highlight the issue. The Travis CI build will pass once #547 is merged.

**Closed** 2018-03-15 22:50 UTC
Labels: bug, needs review
