### ISSUE TITLE
GeoJSON: Character display issues

### ISSUE THREAD

**Issue by balhar-jakub** [NASAWorldWind/WebWorldWind#320] opened 2017-11-15 13:07 UTC
### Description

Some of the characters are loaded improperly in the case of the names of the cities such as Reykjavik.

### Operating System and Version

Windows 10 / Edge 40

**Comment by claudiaifrim** [comment] 2017-11-20 13:48
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0
![canvas](https://user-images.githubusercontent.com/4428527/33021349-3951b8be-ce0a-11e7-8f1f-284e2a481ffe.png)

**Comment by claudiaifrim** [comment] 2018-01-17 12:30
See pull request https://github.com/NASAWorldWind/WebWorldWind/pull/450

**Comment by AkeluX** [comment] 2018-02-21 13:49
Here is how it looks like with the re-encoded test data of #450.

<img width="408" alt="screen shot 2018-02-21 at 14 48 56" src="https://user-images.githubusercontent.com/374540/36483430-61fa00c8-1716-11e8-9a4b-acae8c11cad2.png">

**Comment by AkeluX** [comment] 2018-02-23 19:25
Fixed via the action taken in #450.

**Closed by AkeluX** 2018-02-23 19:25 UTC
Labels: bug, needs review
