### ISSUE TITLE
Firefox: The character encoding of the HTML document was not declared

### ISSUE THREAD

**Issue by claudiaifrim** [NASAWorldWind/WebWorldWind#760] opened 2018-06-24 15:15 UTC
### Description

If you open any example in Firefox you will receive this error in the console:

"The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol."

### Steps to Reproduce

1. Open any example in Firefox browser.

**Reproduces how often:** 100%

### Operating System and Version

Linux Mint 18.2, Firefox 58.0

### Additional Information

To fix this the meta tag above should be inserted in head of html example files.

< meta charset="utf-8" / >

**Comment by pdavidc** [comment] 2018-07-13 22:58
@claudiaifrim Thanks for catching this. Is this issue a duplicate of #364?

**Comment by claudiaifrim** [comment] 2018-07-17 22:38
Yep, it's duplicate.
I will create a pull request for #364

**Closed** 2018-07-24 23:32 UTC
Labels: bug, esa, needs review
