### ISSUE TITLE
Win7+Internet Explorer: GeoJSON example invalid object

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#358] opened 2017-11-17 23:32 UTC
### Description

When running the GeoJSON example, the example stops loading with the following error:

GeoJSON.parse: invalidGeoJSONObject.

### Operating System and Version

Windows 7/IE 11

**Comment by AkeluX** [comment] 2017-11-22 17:16
The problem seems to be a character in the input file that the JSON parser in IE 11 doesn't understand:
> SyntaxError: Invalid character\n   at GeoJSONParser.prototype.parse (http://192.168.99.1:8080/build/dist/worldwind.js:50524:17)\n   at Anonymous function (http://192.168.99.1:8080/build/dist/worldwind.js:50501:25)

**Comment by AkeluX** [comment] 2017-11-22 17:30
The invalid character is in https://worldwind.arc.nasa.gov/web/examples/data/geojson-data/world_main_cities.geojson. I haven't identified which one.

@pdavidc @markpet49, as this is not a bug in the GeoJSON parser itself, I propose to postpone this issue.

**Comment by markpet49** [comment] 2017-11-22 20:04
@AkeluX FYI, I researched this a bit and it appears to be related to a size limitation for JSON strings in IE. If you shorten up world_main_cities.geojson, for instance, the problem goes away for that file. Initially, I thought it was related to unix style line endings, but that turned out not to be the case. The reported error message is misleading.

**Comment by pdavidc** [comment] 2017-11-27 17:27
Here's a summary of what we've decided:
• Replace the file world_main_cities.geojson with one small enough to fit within the IE11 JSON size limitation.
• Document the IE11 JSON size limitation in the GeoJSON API docs.

**Comment by AkeluX** [comment] 2017-11-30 15:54
@markpet49 The current world_main_cities.geojson works on IE11 when I serve it from my local computer. I've also discovered that world_borders.geojson is actually 2MB larger than world_main_cities.geojson and works fine from worldwind.arc.nasa.gov. I guess the problem goes away when shortening the file because we remove the problem from the file, but it does not seem related to its size.

@pdavidc I propose to go ahead with the release plan and continue investigating the cause for this issue independently. What do you think?

**Comment by pdavidc** [comment] 2017-11-30 17:09
@AkeluX This sounds good to me.

**Comment by markpet49** [comment] 2017-12-10 03:11
@AkeluX Hi Yann. I dug in to this some more. You are correct that it is not size related. There are a number of non-ASCII characters in the file. To see the differences, I executed the following commands (on unix):

`cat -v wmc.geojson >wmc-cat.geojson`
`diff wmc-geojson wmc-cat.geojson`

A quick fix is to clean the file with the following command:

`tr -cd "\11\12\15\40-\176" <wmc.geojson >wmc-clean.geojson`

After this, the file loaded fine, but some of the place names with non-ASCII characters may have spelling issues.

**Comment by AkeluX** [comment] 2017-12-13 07:20
Thank you for looking deeper into this. Just as a thought, could it be that this file is encoded differently, e.g. UTF-8 vs UTF-16?

**Comment by markpet49** [comment] 2017-12-13 18:56
@AkeluX Good thought, but many of the occurrences look suspiciously like garbage characters. Examples (with an asterisk at the non-printable character position): "Amundsen*Scott South Pole Station" and "San Mart*n Station". I estimate about 100 lines out of 1200 have the issue.

**Comment by AkeluX** [comment] 2018-02-23 19:25
Fixed via the action taken in #450.

**Closed by AkeluX** 2018-02-23 19:25 UTC
Labels: bug, needs review
