### ISSUE TITLE
SurfaceShapes example: Consider making the polyline thicker

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#341] opened 2017-11-16 23:52 UTC
### Description

The polyline in SurfaceShapes example is hard to see. Making it thicker (increasing its outlineWidth) would make the example more descriptive.

This is also related to #335. When the polyline's outlineWidth is increased from 1, the highlighting works OK. A value of 5 makes it easily observable and hoverable.
### Operating System and Version

Windows 10/Chrome 62

**Comment by markpet49** [comment] 2017-11-20 23:53
@pdavidc pointed out that the root cause of the line picking issue is picking not being able to handle the anti-aliasing around lines and should be fixed by addressing that issue as opposed to masking it with thicker lines.

**Closed by markpet49** 2017-11-20 23:53 UTC
Labels: release-0.9.0
